Repository HimanshuSingh02/Page, pull requests merged in 2022-10, with the labels that each got.

#2 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 A webpage of street dog charity site added
  index.html
Labels: hacktoberfest-accepted

#9 Create Notes.js
  server/Controllers/Notes.js
Labels: hacktoberfest-accepted

#11 Create notes.js
  server/models/notes.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
